---
#
# Create a new NFS enabled SVM
# 
# 1. Create a new SVM with NFS volume
# 2. Update the export-policy of SVM's root volume
# 3. Configure LDAP (optional) | Lightweight Directory Access Protocol
# 4. Verification, NFS access from UNIX host

- name: Create a new SVM
  na_ontap_svm:
    state: present
    name: "{{ netapp_vserver }}"
    root_volume: svm1_root
    root_volume_aggregate: aggr1_cluster_1_01
    root_volume_security_style: unix
    allowed_protocols: [nfs, cifs]
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false

- name: Create a Data LIF
  na_ontap_interface:
    state: present
    interface_name: "{{ vserver }}_data_lif"
    home_port: "{{ LIF_homeport }}"
    home_node: "{{ netapp_node1 }}" # taking the first node as the home node for now
    role: data
    protocols: [nfs, cifs]
    firewall_policy: mgmt-nfs
    address: "{{ LIF_address1 }}"
    netmask: "{{ LIF_netmask }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: "{{ netapp_vserver }}"
    https: true
    validate_certs: false

# - name: Create Data LIFs
#   na_ontap_interface:
#     state: present
#     interface_name: "{{ item.0 }}"
#     home_port: e0c
#     home_node: "{{ item.1 }}"
#     role: data
#     protocols: [nfs, cifs]
#     firewall_policy: mgmt-nfs
#     address: "{{ item.2 }}"
#     netmask: "{{ LIF_netmask }}"
#     hostname: "{{ netapp_hostname }}"
#     username: "{{ netapp_username }}"
#     password: "{{ netapp_password }}"
#     vserver: "{{ netapp_vserver }}"
#     https: true
#     validate_certs: false
#   with_together:
#     - ["{{ vserver }}_data_lif_1" , "{{ vserver }}_data_lif_2"]
#     - ["{{ netapp_node1 }}" , "{{ netapp_node2 }}"] 
#     - ["{{ LIF_address1 }}", "{{ LIF_address2 }}"]

- name: Create NFS server
  na_ontap_nfs:
    state: present
    service_state: started
    nfsv3: enabled
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: "{{ netapp_vserver }}"
    https: true
    validate_certs: false

- import_tasks: ./SVM3.yml
