#
# To-do: Existing SVM without NFS enabled
# 1. Add NFS access to existing SVM
# 2. Define export-policy
# 3. Configure LDAP(optional)
# 4. Verification, NFS access from UNIX host
# 5. Setting up and verify NFS access from client.
#

- name: Modify existing SVM
  na_ontap_svm:
    state: present
    name: "{{ netapp_vserver }}"
    allowed_protocols: [nfs, cifs]
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false

- name: Create a Data LIF
  na_ontap_interface:
    state: present
    interface_name: "{{ vserver }}_data_lif"
    home_port: "{{ LIF_homeport }}"
    home_node: "{{ netapp_node1 }}" # taking the first node as the home node for now
    role: data
    protocols: [nfs, cifs]
    firewall_policy: mgmt-nfs
    address: "{{ LIF_address }}"
    netmask: 255.255.255.0
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: "{{ netapp_vserver }}"
    https: true
    validate_certs: false