#
# To-do: Existing SVM without NFS enabled
# 1. Add NFS access to existing SVM
# 2. Define export-policy
# 3. Configure LDAP(optional)
# 4. Verification, NFS access from UNIX host
# 5. Setting up and verify NFS access from client.
#

- name: Modify existing SVM
  na_ontap_svm:
    state: present
    name: "{{ netapp_vserver }}"
    allowed_protocols: [nfs, cifs]
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false

- name: Create a Data LIF
  na_ontap_interface:
    state: present
    interface_name: "{{ vserver }}_data_lif"
    home_port: "{{ LIF_homeport }}"
    home_node: "{{ netapp_node1 }}" # taking the first node as the home node for now
    role: data
    protocols: [nfs, cifs]
    firewall_policy: mgmt-nfs
    address: "{{ LIF_address }}"
    netmask: 255.255.255.0
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: "{{ netapp_vserver }}"
    https: true
    validate_certs: false

- name: Create NFS server
  na_ontap_nfs:
    state: present
    service_state: started
    nfsv3: enabled
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: "{{ netapp_vserver }}"
    https: true
    validate_certs: false

- name: Create Default ExportPolicyRule 
  na_ontap_export_policy_rule:
    state: present
    name: default
    client_match: 0.0.0.0/0
    ro_rule: any
    rw_rule: none
    rule_index: 1
    protocol: nfs
    super_user_security: none
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: "{{ netapp_vserver }}"  
    https: true
    validate_certs: false

- name: Create Export Policy
  na_ontap_export_policy:
    state: present
    name: "{{ netapp_vol1 }}"
    vserver: "{{ netapp_vserver }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false

- name: Create ExportPolicyRule
  na_ontap_export_policy_rule:
    state: present
    name: "{{ netapp_vol1 }}"
    client_match: 0.0.0.0/0
    ro_rule: any
    rw_rule: any
    rule_index: 1
    protocol: nfs
    super_user_security: any
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: "{{ netapp_vserver }}"  
    https: true
    validate_certs: false

- name: Create FlexVol
  na_ontap_volume:
    state: present
    name: "{{ netapp_vol1 }}"
    aggregate_name: aggr1_cluster_1_01
    size: 10
    size_unit: gb
    space_guarantee: none
    policy: "{{ netapp_vol1 }}"
    percent_snapshot_space: 5
    junction_path: /{{ netapp_vol1 }}
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: "{{ netapp_vserver }}"      
    https: true
    validate_certs: false