---
#
# Existing SVM with NFS config
#
# 1. Create and configure a volume
# 2. Create export-policy for the volume
# 3. Verification, NFS access from UNIX host
# 4. Setting up and verify NFS access from client.
#
- name: Create Default ExportPolicyRule 
  na_ontap_export_policy_rule:
    state: present
    name: default
    client_match: 0.0.0.0/0
    ro_rule: any
    rw_rule: none
    rule_index: 1
    protocol: nfs
    super_user_security: none
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: "{{ netapp_vserver }}"  
    https: true
    validate_certs: false

- name: Create Export Policy
  na_ontap_export_policy:
    state: present
    name: "{{ netapp_vol1 }}"
    vserver: "{{ netapp_vserver }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false

- name: Create ExportPolicyRule
  na_ontap_export_policy_rule:
    state: present
    name: "{{ netapp_vol1 }}"
    client_match: 0.0.0.0/0
    ro_rule: any
    rw_rule: any
    rule_index: 1
    protocol: nfs
    super_user_security: any
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: "{{ netapp_vserver }}"  
    https: true
    validate_certs: false

- name: Create FlexVol
  na_ontap_volume:
    state: present
    name: "{{ netapp_vol1 }}"
    aggregate_name: aggr1_cluster_1_01
    size: 10
    size_unit: gb
    space_guarantee: none
    policy: "{{ netapp_vol1 }}"
    percent_snapshot_space: 5
    junction_path: /{{ netapp_vol1 }}
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: "{{ netapp_vserver }}"      
    https: true
    validate_certs: false
    
    

