--- 
- hosts: localhost
  gather_facts: no
  become: true
  vars:
    netapp_hostname: 192.168.123.11 #ONTAP Cluster
    netapp_username: admin 
    netapp_password: cluster1
  tasks: 
  - name: Install netapp-lib
    pip:
      name: netapp-lib
      state: present
  
  - name: Create Aggregates and wait 5 minutes until aggregate is online
    na_ontap_aggregate:
      state: present
      service_state: online
      name: "{{ item }}"
      disk_count: 5
      wait_for_online: True
      time_out: 300
      nodes: cluster-1-01
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    with_items:
      - aggr1_cluster01
      - aggr1_cluster02

