--- 
- hosts: localhost
  name: Volume Action
  vars:
    hostname: 192.168.0.101 #ONTAP Cluster
    username: admin 
    password: Netapp1!
    # vserver: vserver1  #vserver
    # aggr: aggr1   #aggregate
    vol_name: ansibleVol
  
  tasks:
  - name: Creating a volume
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      # vserver: "{{ vserver }}"
      # aggregate_name: "{{ aggr }}"
      size: 10
      size_unit: gb
      policy: default
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false