--- 
- hosts: localhost
  name: Volume Action
  vars:
    hostname: 172.32.0.182 #ONTAP Cluster
    username: admin 
    password: netapp123
    vserver: vserver1  #vserver
    aggr: aggr1   #aggregate
    vol_name: ansibleVol
  tasks:
  - name: Install pip
    pip:
      name: netapp-lib

  - name: Creating a volume
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 10
      size_unit: gb
      policy: default
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
