--- 
- hosts: localhost
  gather_facts: no
  become: true
  vars:
    netapp_hostname: 192.168.123.11 #ONTAP Cluster
    netapp_username: admin 
    netapp_password: cluster1
  tasks: 
  - name: Install netapp-lib
    pip:
      name: netapp-lib
      state: present
  
  - name: Create Aggregates and wait 5 minutes until aggregate is online
    na_ontap_aggregate:
      state: present
      service_state: online
      name: "{{ item }}"
      disk_count: 5
      wait_for_online: True
      time_out: 300
      nodes: cluster-1-01
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    with_items:
      - aggr1_cluster01
      - aggr1_cluster02

  - name: Create subnet
    na_ontap_net_subnet:
      state: present
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      hostname: "{{ netapp_hostname }}"
      subnet: 192.168.0.0/24
      name: Demo
      ip_ranges: [ '192.168.0.131-192.168.0.192']
      gateway: 192.168.0.1
      ipspace: Default
      broadcast_domain: Default
      https: true
      validate_certs: false

  - name: Create SVM
    na_ontap_svm:
      state: present
      name: svm1
      root_volume: svm1_root
      root_volume_aggregate: aggr1_cluster01
      root_volume_security_style: ntfs
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      # allowed_protocols: nfs, cifs
      https: true
      validate_certs: false
