---
#
# Create a new SVM
# 
- name: Create a new SVM
  na_ontap_svm:
    state: present
    name: "{{ vserver }}"
    root_volume: svm1_root
    root_volume_aggregate: "{{ vol_aggr }}"
    root_volume_security_style: unix
    allowed_protocols: [iscsi]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    https: true
    validate_certs: false
  when: create_new_vserver == true

#
# Existing SVM without NFS enabled
#
- name: Modify existing SVM
  na_ontap_svm:
    state: present
    name: "{{ vserver }}"
    allowed_protocols: [iscsi]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    https: true
    validate_certs: false
  when: create_new_vserver == false

- name: Create a Data LIF
  na_ontap_interface:
    state: present
    interface_name: "{{ item.1 }}"
    home_port: "{{ LIF_homeport }}"
    home_node: "{{ item.0 }}" 
    role: data
    protocols: [iscsi]
    firewall_policy: mgmt-nfs
    address: "{{ item.2 }}"
    netmask: "{{ LIF_netmask }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vserver: "{{ vserver }}"
    https: true
    validate_certs: false
  with_together:
    - ["{{ node1 }}", "{{ node2 }}"]
    - ["{{ vserver }}_data_lif1", "{{ vserver }}_data_lif2"]
    - ["{{ LIF_address1 }}", "{{ LIF_address2 }}"]
  when: create_new_vserver == false

- import_tasks: ./volume.yml

- name: Create LUN
  na_ontap_lun:
    state: present
    name: "{{ LUN_name }}"
    flexvol_name: "{{ vol }}"
    size: "{{ LUN_size }}"
    size_unit: gb
    ostype: "{{ LUN_os }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vserver: "{{ vserver }}"
    https: true
    validate_certs: false

- name: Create/Configure iSCSI service
  na_ontap_iscsi:
    state: present
    service_state: started
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vserver: "{{ vserver }}"
    https: true
    validate_certs: false

- name: Create iSCSI Igroup
  na_ontap_igroup:
    state: present
    name: "{{ Igroup_name }}"
    initiator_group_type: iscsi
    ostype: "{{ OS_type }}"
    initiators: "{{ Initiator }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vserver: "{{ vserver }}"
    https: true
    validate_certs: false

- name: Create LUN mapping
  na_ontap_lun_map:
    state: present
    initiator_group_name: "{{ Igroup_name }}"
    path: "{{ LUN_path }}" 
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vserver: "{{ vserver }}"
    https: true
    validate_certs: false
