---
- name: Create intercluster LIFs
  na_ontap_interface:
    state: present
    interface_name: "{{cluster}}_ilif1"
    home_port: "{{ LIF_homeport }}"
    home_node: "{{ node1 }}"
    role: data
    protocols: [nfs, cifs]
    firewall_policy: mgmt-nfs
    address: "{{ LIF_address1 }}"
    netmask: "{{ LIF_netmask }}"
    vserver: "{{ cluster }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    https: true
    validate_certs: false
  
# - name: Create a Data LIF
#   na_ontap_interface:
#     state: present
#     interface_name: "{{ vserver }}_data_lif"
#     home_port: "{{ LIF_homeport }}"
#     home_node: "{{ node1 }}" # taking the first node as the home node for now
#     role: data
#     protocols: [nfs, cifs]
#     firewall_policy: mgmt-nfs
#     address: "{{ LIF_address1 }}"
#     netmask: "{{ LIF_netmask }}"
