---
#
# Create a new NFS enabled SVM
# 
- name: Create a new SVM
  na_ontap_svm:
    state: present
    name: "{{ vserver }}"
    root_volume: svm1_root
    root_volume_aggregate: "{{ vol_aggr }}"
    root_volume_security_style: unix
    allowed_protocols: [nfs, cifs]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    https: true
    validate_certs: false
  when: create_new_vserver == true

#
# Existing SVM without NFS enabled
#
- name: Modify existing SVM
  na_ontap_svm:
    state: present
    name: "{{ vserver }}"
    allowed_protocols: [nfs, cifs]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    https: true
    validate_certs: false
  when: create_new_vserver == false

- name: Create DNS
  na_ontap_dns:
    state: present
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vserver:  "{{ vserver }}"
    domains: "{{ dns_domain }}"
    nameservers: 192.168.123.136 ## currently IP of the winServer
    skip_validation: true
    https: true
    validate_certs: false

- name: Create CiFS Server
  na_ontap_cifs_server:
    state: present
    cifs_server_name: "{{ vserver }}"
    domain: "{{ dns_domain }}"
    admin_user_name: "{{ ad_username }}" #AD server
    admin_password: "{{ ad_password }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vserver: "{{ vserver }}"
    https: true
    validate_certs: false

- import_tasks: ./volume.yml