---
#
# Create a new NFS enabled SVM
# 
- name: Create a new SVM
  na_ontap_svm:
    state: present
    name: "{{ vserver }}"
    root_volume: svm1_root
    root_volume_aggregate: "{{ vol }}"
    root_volume_security_style: unix
    allowed_protocols: [nfs, cifs]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    https: true
    validate_certs: false
  when: create_new_vserver == true

#
# Existing SVM without NFS enabled
#
- name: Modify existing SVM
  na_ontap_svm:
    state: present
    name: "{{ vserver }}"
    allowed_protocols: [nfs, cifs]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    https: true
    validate_certs: false
  when: create_new_vserver == false

- name: Create a Data LIF
  na_ontap_interface:
    state: present
    interface_name: "{{ vserver }}_data_lif"
    home_port: "{{ LIF_homeport }}"
    home_node: "{{ node1 }}" # taking the first node as the home node for now
    role: data
    protocols: [nfs, cifs]
    firewall_policy: mgmt-nfs
    address: "{{ LIF_address1 }}"
    netmask: "{{ LIF_netmask }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vserver: "{{ vserver }}"
    https: true
    validate_certs: false

- name: Create NFS server
  na_ontap_nfs:
    state: present
    service_state: started
    nfsv3: enabled
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vserver: "{{ vserver }}"
    https: true
    validate_certs: false

- import_tasks: ./volume.yml
